### ISSUE TITLE
Request: mock() variant that die()s if the original is undefined

### ISSUE THREAD

**Issue by FGasper** [geofffranks/test-mockmodule#17]
Generally when I see this module used it’s to redefine a method; if the original method doesn’t exist, then the test is testing itself rather than the production code.

It would be great to have:
```
$mocker->redefine( NAME, CODEREF )
```
… identical to `mock()` but with a die() if the original function doesn’t exist. That way the test can complain if the object internals have changed such that the test is no longer flexing the code properly.

Thoughts?

**Comment by geofffranks** [comment]
What about an import flag to turn that on as a feature inside mock? Any reason you would want to mock some calls and redefine others?

**Comment by FGasper** [comment]
Personally, I can’t see a reason to *want* the behavior that creates a new function, so yeah, I’d probably always set the flag.

Maybe an import flag, like:
```
use Test::MockModule qw( die_on_create );
```

**Comment by geofffranks** [comment]
Cool, I probably won't get to this for a bit, but if you want to submit a PR, I can push it through relatively quick

**Comment by geofffranks** [comment]
I'll release a new version of this tonight, leaving the issue open until then

**Comment by FGasper** [comment]
Thank you, @geofffranks!

**Comment by geofffranks** [comment]
Ok, this should be live shortly. currently being processed by cpan
