### ISSUE TITLE
Mocking exported functions

### ISSUE THREAD

**Issue by eserte** [geofffranks/test-mockmodule#2]
`Test::MockModule` does not work very well with exported functions. Consider the following example:

```
#!/usr/bin/perl

use strict;
use warnings;

use POSIX;

use Test::MockModule;
my $mock;
BEGIN {
    $mock = Test::MockModule->new('POSIX');
    # $mock = Test::MockModule->new('main', no_auto => 1);
    $mock->mock(strftime => sub { warn "mocked strftime" });
}

strftime("%F %T", localtime);

$mock->mock(strftime => sub { warn "re-mocked strftime" });

strftime("%F %T", localtime);

__END__
```

In this case `strftime` is not mocked. One has to know that exported functions are imported into the current namespace, so a possible workaround is to use

```
    $mock = Test::MockModule->new('main', no_auto => 1);
```

Another possible workaround is to move the `use POSIX` statement after the `BEGIN` block. In this case the replaced `strftime` is used. But again, re-mocking is not possible here.

I am not sure if `Test::MockModule` can be improved here, but at least the documentation should contain some lines on this topic.

**Comment by geofffranks** [comment]
Added docs to help with mocking exported functions in v0.10. 0.10 has been uploaded to cpan, should be out for distribution shortly.
