### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by ppisar** [geofffranks/test-mockmodule#21]
lib/Test/MockModule.pm states:

~~~
You may distribute under the terms of either the GNU General Public License or
the Artistic License, as specified in the Perl README file.
~~~

LICENSE reads:

~~~
This is free software, licensed under:

  The GNU General Public License, Version 3, June 2007
~~~

May I know what of these two statements are true? Perl  is licensed under GNU GPLv1 or later, or under Artistic License.

**Comment by geofffranks** [comment]
The license in lib/Test/MockModule is the correct info. build.pl + the LICENSE file have been updated accordingly.
