### ISSUE TITLE
We should be able to mock CORE::GLOBAL without checking INC

### ISSUE THREAD

**Issue by atoomic** [geofffranks/test-mockmodule#25]
We should not check %INC in this case
```
> perl -MTest::MockModule -E 'Test::MockModule->new( "CORE::GLOBAL" )'
Can't locate CORE/GLOBAL.pm in @INC (you may need to install the CORE::GLOBAL module)
```

So we could easily mock CORE functions like system for example.

**Comment by skirmess** [comment]
@atoomic Do you have a working example on how to mock system?

**Comment by atoomic** [comment]
@skirmess here is a basic example to mock `system`, but you could consider using [Test::Mock::Cmd](https://metacpan.org/pod/Test::Mock::Cmd)

```perl
#!perl

use v5.14;

BEGIN {
	*CORE::GLOBAL::system = sub { qw{mocked ...} };	
}

say system('date');
```
