### ISSUE TITLE
[Feature Request] Allow chaining of mocking functions after new

### ISSUE THREAD

**Issue by atoomic** [geofffranks/test-mockmodule#34]
The idea is to be able to do something like this

```perl
# use redefine after a new
my $mock = Test::MockModule->new( 'MyModule' )->redefine( myfunction => 42 );

# which could also allow something like this
my $mock = Test::MockModule->new( 'MyModule' )
                     ->redefine( myfunction => 42 )
                     ->define( missing function => sub { ... } );
```

Same with all other functions like `define`, `mock`,...

As it stands `redefine` just returns the `_mock` which does not have a clear return value, so this sounds doable with a simple patch.

I think the implementation is pretty easy, can also add some tests...
probably more time updating the doc than anything else.

@geofffranks would you be open to something like this? if so I can provide a prototype

**Comment by geofffranks** [comment]
Totally open to this, if you're still interested in making a PR for it

**Comment by atoomic** [comment]
totally open to this, will come with something later :-)
thanks for your feedback
