### ISSUE TITLE
import() should check for unknown imports

### ISSUE THREAD

**Issue by perlpunk** [geofffranks/test-mockmodule#45]
We had an issue with using the `strict` option.
In one of CI systems we have Test::MockModule 0.13, and the other CI and developers have the newest version.
Because the `import` function does not check if unknown symbols are imported, we never got a warning that `strict` is not supported in this version.
Additionally I think that this code could be improved:
```
$STRICT_MODE = 1 if ( grep { $_ =~ m/strict/i } @args );
```
It allows something like `use Test::MockModule 'noSTRICT` for example.
Is there a reason not just allowing `strict` and die for anything else?

**Comment by atoomic** [comment]
I'm not aware of any cases requiring the regexp instead of a strict equality. Even the case insensitive should not be required and we should consider using

`$STRICT_MODE = 1 if grep { $_ eq q[strict] } @args;`

**Comment by geofffranks** [comment]
Thanks for the fix @atoomic !

Released in 0.173.0 which should publish shortly
