### ISSUE TITLE
Strict mode should be lexically scoped

### ISSUE THREAD

**Issue by davidcantrell-bb** [geofffranks/test-mockmodule#53]
If I use T::MM in two places at the same time, and turn on strict mode in one, my `mock()`s start failing in the other. There are legitimate reasons to still use `mock()`, such as where the sub being mocked is inserted in crazy magical places by Mojo, or if it is used in some third-party libs that you can't change.

**Comment by davidcantrell-bb** [comment]
Expect a pull request ... some time :-)

**Comment by geofffranks** [comment]
Awesome, thanks!

**Comment by DrHyde** [comment]
https://github.com/geofffranks/test-mockmodule/pull/54

**Comment by DrHyde** [comment]
any comments on the PR? It would be really handy if it could be merged, as I can then not worry about maintaining my local patched fork.

**Comment by DrHyde** [comment]
this can be closed now

**Comment by geofffranks** [comment]
Oops, thanks!
