### ISSUE TITLE
Move test modules to test requires phase

### ISSUE THREAD

**Issue by oalders** [geofffranks/test-mockmodule#56]
Hi. Thanks for your work!

I noticed this today:

https://metacpan.org/release/GFRANKS/Test-MockModule-v0.176.0/source/META.json#L18-23

It would be great if modules which are only needed to run tests would appear in test requires instead. The motivation is that I'm trying to remove test dependencies from a DarkPAN. When test requirements appear as build or runtime requirements it becomes harder to automate pruning test distributions.

**Comment by geofffranks** [comment]
Seems reasonable. Any chance you can PR this?

**Comment by oalders** [comment]
Sure. I'll take a look after Labour Day.
