### ISSUE TITLE
Use of uninitialized value within %symbols in ref-to-glob cast at .../Test/MockModule.pm line 235 during global destruction.

### ISSUE THREAD

**Issue by XSven** [geofffranks/test-mockmodule#59]
I am working with `perl` 5.14.4 and `Test::MockModule` 0.177.0

I have changed a class from raw `perl` oo style to `Moo`. I have used `namespace::clean` 0.27. The unit tests that use `Test::MockModule`  annoyingly raise now warnings

> Use of uninitialized value within %symbols in ref-to-glob cast at .../Test/MockModule.pm line 235 during global destruction.

that  refers to the code line.

`+235 next unless defined(my $elem = *{$symbols{$sub}}{$_}); `

How could this be avoided?

**Comment by atoomic** [comment]
probably by adding a protection for `$symbols{$sub}` 
that should fix it?
```
next unless defined $symbols{$sub} && defined(my $elem = *{$symbols{$sub}}{$_}); 
```

**Comment by XSven** [comment]
It works thanks. How do we get this fix into the next release?

**Comment by geofffranks** [comment]
If you want to submit a PR for this, I can take a look, merge  and release it.

**Comment by atoomic** [comment]
Going to submit one :-)

**Comment by geofffranks** [comment]
Ok, this should be released and available on cpan now. lmk if there're any issues, but i'm away for the weekend.

**Comment by atoomic** [comment]
Thanks
